{{- if .Values.server.autoscaling.enabled }}
{{- $services := list "frontend" "history" "matching" }}
{{- range $service := $services }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "temporal.fullname" $ }}-{{ $service }}
  labels:
    {{- include "temporal.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "temporal.fullname" $ }}-{{ $service }}
  minReplicas: {{ index $.Values.server.autoscaling $service "minReplicas" }}
  maxReplicas: {{ index $.Values.server.autoscaling $service "maxReplicas" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ index $.Values.server.autoscaling $service "targetCPUUtilizationPercentage" }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
{{- end }}
{{- end }}
